[project]
name = "lts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.6.8, <3.9"
dependencies = [
    "altgraph==0.17.3",
    "astroid==2.11.7",
    "autopep8==1.6.0",
    "certifi==2022.12.7",
    "charset-normalizer==2.0.12",
    "click==8.0.4",
    "colorama==0.4.5",
    "dill==0.3.4",
    "docopt==0.6.2",
    "flake8==4.0.1",
    "future==0.18.2",
    "idna==3.4",
    "importlib-metadata==4.2.0",
    "isort==5.10.1",
    "jedi==0.18.2",
    "lazy-object-proxy==1.7.1",
    "mccabe==0.6.1",
    "numpy==1.19.5",
    "pandas==1.1.5",
    "parso==0.8.3",
    "pefile==2022.5.30",
    "pipreqs==0.4.11",
    "platformdirs==2.4.0",
    "pluggy==1.0.0",
    "pyarmor==7.3.1",
    "pycodestyle==2.8.0",
    "pydocstyle==6.1.1",
    "pyflakes==2.4.0",
    "pyinstaller==4.10",
    "pyinstaller-extractor==1.0.3",
    "pyinstaller-hooks-contrib==2022.0",
    "pylint==2.13.9",
    "pyserial==3.5",
    "pyside2==5.15.2.1",
    "python-dateutil==2.8.2",
    "python-lsp-jsonrpc==1.0.0",
    "python-lsp-server==1.3.3",
    "pytz==2023.3.post1",
    "pywin32-ctypes==0.2.0",
    "requests==2.27.1",
    "rope==1.1.1",
    "shiboken2==5.15.2.1",
    "six==1.16.0",
    "snowballstemmer==2.2.0",
    "spark-parser==1.8.9",
    "toml==0.10.2",
    "tomli==1.2.3",
    "typed-ast==1.5.4",
    "typing-extensions==4.1.1",
    "ujson==4.3.0",
    "uncompyle6==3.8.0",
    "urllib3==1.26.13",
    "wrapt==1.14.1",
    "xdis==6.0.4",
    "yapf==0.32.0",
    "yarg==0.1.9",
    "zipp==3.6.0",
]

[dependency-groups]
dev = [
    "pyinstaller>=4.10",
    "pyside6>=6.3.2",
]
